### ISSUE TITLE
Decoder streams do not work in flowing mode in Node 10+

### ISSUE THREAD

**Issue by Rantanen** [TooTallNate/node-ogg#16]
Mostly this is for information.

The underlying issue is a Node.js issue (https://github.com/nodejs/node/issues/24915), but since `node-ogg` seems to be one of the few libraries that combines the `highWaterMark: 0` with asynchronous `push()`, it doesn't seem to be widely encountered.

I mean.. it's apparently been broken for 2 Node releases... :)

One possible workaround for `node-ogg` would be to use `highWaterMark: 1` for the DecoderStream. On the other hand, I'm expecting the issue to be fixed in Node at some point anyway.

**Comment by TooTallNate** [comment]
Thanks for the explanation. Looks like this was fixed in Node (https://github.com/nodejs/node/commit/37a5e01bda104eacca78da31afb9f9ec05da180c), so closing.
